checkboxes:
  Anoxic_injury_checkbox: Anoxic injury
  Brain_edema_checkbox: Brain edema
  Craniectomy_checkbox: Craniectomy
  Craniotomy_checkbox: Craniotomy
  EDH_checkbox: EDH
  EVD_checkbox: EVD
  ICH_checkbox: ICH
  IVH_checkbox: IVH
  Infarct_checkbox: Infarct
  Intra_axial_tumor_checkbox: Intra-axial tumor
  Menigioma_checkbox: Meningioma
  Metal_artifact_checkbox: Metal artifact
  Midline_shift_checkbox: Midline shift
  Motion_artifact_checkbox: Motion artifact
  Multiple_lesions_checkbox: Multiple lesions
  Normal_checkbox: Normal
  Pressure_monitor_checkbox: Pressure monitor
  SAH_checkbox: SAH
  SDH_checkbox: SDH
  Tonsillar_herniation_checkbox: Tonsillar herniation
comboboxes:
  atrophy:
    atrophy_mild: Mild
    atrophy_moderate: Moderate
    atrophy_none: None
    atrophy_severe: Severe
  ventricular_size:
    ventricular_size_mild: Mild
    ventricular_size_moderate: Moderate
    ventricular_size_normal: Normal/proportional
    ventricular_size_severe: Severe
  white_matter_changes:
    wmc_mild: Mild
    wmc_moderate: Moderate
    wmc_none: None
    wmc_severe: Severe
freetextboxes:
  number_of_focal_points: Number of focal points
  other_comments: Comments
