ct_window_level: 45
ct_window_width: 85
default_segmentation_directory: ''
default_volume_directory: ''
impose_bids_format: false
input_filetype: '*.nii.gz'
interpolate_value: 1
is_classification_requested: true
is_keyboard_shortcuts_requested: true
is_mouse_shortcuts_requested: false
is_segmentation_requested: false
is_semi_automatic_phe_tool_requested: true
modality: CT
slice_view_color: Red
