KEYBOARD_SHORTCUTS:
- button: pushButton_ToggleFill
  callback: toggleFillButton
  shortcut: f
- button: pushButton_ToggleVisibility
  callback: onPushButton_ToggleVisibility
  shortcut: v
- button: pushButton_undo
  callback: onPushButton_undo
  shortcut: z
- button: SaveSegmentationButton
  callback: onSaveSegmentationButton
  shortcut: s
- button: pushButton_Smooth
  callback: onPushButton_Smooth
  shortcut: l
- button: pushButton_Small_holes
  callback: onPushButton_Small_holes
  shortcut: o
- button: pushButton_Interpolate
  callback: onPushButton_Interpolate
  shortcut: i
